export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_LIST = "FETCH_LIST";
export const FETCH_LIST_FAIL = "FETCH_LIST_FAIL";
export const FETCH_LIST_RECENT = "FETCH_LIST_RECENT";
export const FETCH_LIST_POPULAR = "FETCH_LIST_POPULAR";
export const FETCH_LIST_CLEAR = "FETCH_LIST_CLEAR";


export const FETCH_NOTI ="FETCH_NOTI";
export const FETCH_NOTI_SUCCESS ="FETCH_NOTI_SUCCESS";

export const FETCH_POST ="FETCH_POST";
export const FETCH_POST_FAIL ="FETCH_POST_FAIL";
export const FETCH_POST_SUCCESS ="FETCH_POST_SUCCESS";
export const FETCH_POST_CLEAR ="FETCH_POST_CLEAR";
export const FETCH_POST_SET_COMMENT = "FETCH_POST_SET_COMMENT";
export const FETCH_POST_ADD_COMMENT ="FETCH_POST_ADD_COMMENT";
export const FETCH_POST_OLD_COMMENT ="FETCH_POST_OLD_COMMENT";
export const FETCH_POST_DELETE_COMMENT = "FETCH_POST_DELETE_COMMENT";
export const FETCH_POST_PREUPLOAD = "FETCH_POST_PREUPLOAD";
export const FETCH_POST_UPLOADED = "FETCH_POST_UPLOADED";

export const FETCH_CONTENT = "FETCH_CONTENT";
export const FETCH_CONTENT_FAIL = "FETCH_CONTENT_FAIL";
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS";
export const FETCH_CONTENT_CLEAR = "FETCH_CONTENT_CLEAR";
export const FETCH_CONTENT_ADD_MODAL = "FETCH_CONTENT_ADD_MODAL"